import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.1)
mengetik('menghubungi UCH 2009..')
mengetik('[-----]10%')
mengetik('[-----]20%')
mengetik('[-----]30%')
mengetik('[-----]40%')
mengetik('[-----]50%')
mengetik('[-----]60%')
mengetik('[-----]70%')
mengetik('[-----]80%')
mengetik('[-----]90%')
mengetik('[-----]100%')
mengetik('mencoba meminta akses sabar ya TOD !')
mengetik('[-----]40%')
mengetik('[-----]50%')
mengetik('[-----]70%')
mengetik('[-----]90%')
mengetik('[----]100%')
mengetik('mengupdate ! sabar ya TOD !')
mengetik('[-----]100%')
mengetik ('jangan berharap lebih ke dia jika dia tidak berharap ke kamu')
mengetik ('BACOT..!!hehe santay gan')
mengetik ('SElESAI UPDATE HEE MAAF MENUGGU SILAKAN MENIKMATI TOOLSNYA')
